# Application Settings
app:
  name: sawmills-collector
  namespace: sawmills

# HPA Settings
hpa:
  # Type of HPA to use (current only keda is supported)
  type: keda
  
  # KEDA specific configuration
  keda:
    enabled: true
    minReplicas: 1
    maxReplicas: 100
    pollingInterval: 30
    cooldownPeriod: 300
    scaling:
      cpu:
        enabled: true
        targetUtilization: 80
      memory:
        enabled: true
        targetUtilization: 80
  

# Ingress Settings
ingress:
  # Type of ingress to use (current only nginx is supported)
  type: nginx
  
  # Nginx specific configuration
  nginx:
    enabled: true
    className: nginx
    # Port to expose the ingress on
    port: 4318 
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: sawmills-collector.local # HOST endpoint for the ingress
        paths:
          - path: /
            pathType: Prefix
