{{- if .Values.rbac.createRoleBinding }}
{{- if not .Values.rbac.roleBindingName }}
{{- fail "roleBindingName must be set when createRoleBinding is true" }}
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.roleBindingName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
