{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sawmills-remote-operator.fullname" . }}
  labels:
    {{- include "sawmills-remote-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sawmills-remote-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsService.port }}
      targetPort: {{ .Values.metricsService.targetPort }}
      protocol: TCP
{{- end }}
