{{- if not .Values.apiKeyExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: remote-operator
type: Opaque
data:
  api-key: {{ required "apiKey must be set when apiKeyExistingSecret is empty" .Values.apiKey | b64enc }}
{{- end }}
