{{- if and (eq .Values.ingress.type "nginx") .Values.ingress.nginx.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sawmills-collector.fullname" . }}-nginx-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.nginx.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.nginx.className }}
  {{- if .Values.ingress.nginx.tls }}
  tls:
    {{- toYaml .Values.ingress.nginx.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.nginx.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "sawmills-collector.fullname" $ }}
                port:
                  number: {{ $.Values.ingress.nginx.port }}
          {{- end }}
    {{- end }}
{{- end }} 