{{- if .Values.kedaScaler.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sawmills-collector.fullname" . }}-otel-scaler-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sawmills-collector.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- with .Values.kedaScaler.config }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}