{{- if and .Values.loadBalancer.enabled .Values.loadBalancer.service.headless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sawmills-collector.fullname" . }}-headless
  labels:
    {{- include "sawmills-collector.loadBalancerLabels" . | nindent 4 }}
  {{- if .Values.loadBalancer.service.annotations }}
  annotations:
    {{- toYaml .Values.loadBalancer.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ClusterIP: None
  {{- if .Values.loadBalancer.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.loadBalancer.service.internalTrafficPolicy }}
  {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.telemetry.prometheus.port }}
      targetPort: {{ .Values.telemetry.prometheus.port }}
      name: prometheus
    {{- range $name, $config := .Values.loadBalancer.service.ports }}
    - protocol: {{ $config.to.protocol }}
      port: {{ $config.to.port }}
      targetPort: {{ $config.from }}
      name: {{ $name }}
    {{- end }}
    {{- if eq (include "sawmills-collector.siblingFallbackEnabled" .) "true" }}
    {{- range $name, $config := .Values.haproxy.mapping }}
    - protocol: TCP
      port: {{ $config.from }}
      targetPort: {{ $config.from }}
      name: {{ printf "hp-%d" (int $config.from) }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "sawmills-collector.loadBalancerSelectorLabels" . | nindent 4 }}
{{- end }}