{{- $lbTelemetryOtelConfig := default dict .Values.loadBalancer.telemetryOtelConfig }}
{{- if and .Values.loadBalancer.enabled (not (default "" $lbTelemetryOtelConfig.s3path)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sawmills-collector.fullname" . }}-load-balancer-telemetry-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sawmills-collector.labels" . | nindent 4 }}
data:
  telemetry-config.yaml: |
    {{- if or .Values.telemetryConfig .Values.loadBalancer.telemetryConfig }}
      {{- include "sawmills-collector.loadBalancerTelemetryConfig" . | nindent 6 }}
    {{- end }}
{{- end }}
