{{- if .Values.remoteOperatorMetricsScrape.enabled }}
{{- $remoteOperatorNamespace := default .Release.Namespace .Values.remoteOperatorMetricsScrape.namespace -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sawmills-collector.fullname" . }}-remote-operator-scrape
  namespace: {{ $remoteOperatorNamespace }}
  labels:
    {{- include "sawmills-collector.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sawmills-collector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sawmills-collector.fullname" . }}-remote-operator-scrape
{{- end }}
