{{- if .Values.kedaScaler.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sawmills-collector.fullname" . }}-telemetry-keda-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sawmills-collector.labels" . | nindent 4 }}
data:
  keda.yaml: |
    {{- with .Values.kedaScaler.telemetryConfig }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
