{{- $telemetryOtelConfig := default dict .Values.telemetryOtelConfig }}
{{- if not (default "" $telemetryOtelConfig.s3path) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sawmills-collector.fullname" . }}-telemetry-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sawmills-collector.labels" . | nindent 4 }}
data:
  telemetry-config.yaml: |
    {{- if .Values.telemetryConfig }}
      {{- include "sawmills-collector.telemetryConfig" . | nindent 6 }}
    {{- end }}
{{- end }}
