name: Update Chart Version on PR

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  update-chart-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Get main branch version
        id: get_main_version
        run: |
          MAIN_VERSION=$(grep "^version:" helm-charts/sawmills-collector/Chart.yaml | cut -d' ' -f2)
          echo "main_version=${MAIN_VERSION}" >> $GITHUB_OUTPUT
          echo "Main branch Chart.yaml version: ${MAIN_VERSION}"
      
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Calculate next version
        id: calc_version
        run: |
          MAIN_VERSION="${{ steps.get_main_version.outputs.main_version }}"
          
          # Parse semantic version (assuming format like 2.1.0)
          IFS='.' read -r major minor patch <<< "$MAIN_VERSION"
          
          # Default to patch increment (can be made smarter by analyzing PR labels/commits)
          new_minor=$((minor + 1))
          NEXT_VERSION="${major}.${new_minor}.0"
          
          echo "next_version=${NEXT_VERSION}" >> $GITHUB_OUTPUT
          echo "Calculated next version: ${NEXT_VERSION} (from main: ${MAIN_VERSION})"
      
      - name: Update Chart.yaml version
        run: |
          NEXT_VERSION="${{ steps.calc_version.outputs.next_version }}"
          CURRENT_VERSION=$(grep "^version:" helm-charts/sawmills-collector/Chart.yaml | cut -d' ' -f2)
          
          echo "Current version: $CURRENT_VERSION"
          echo "Next version: $NEXT_VERSION"
          
          if [ "$CURRENT_VERSION" != "$NEXT_VERSION" ]; then
            sed -i "s/^version: .*/version: ${NEXT_VERSION}/" helm-charts/sawmills-collector/Chart.yaml
            echo "Updated Chart.yaml version to: $NEXT_VERSION"
          else
            echo "Version already up to date"
            exit 0
          fi
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --quiet helm-charts/sawmills-collector/Chart.yaml; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add helm-charts/sawmills-collector/Chart.yaml
          git commit -m "Update Chart.yaml version to ${{ steps.calc_version.outputs.next_version }}"
          git push origin ${{ github.head_ref }} 